package com.moonsworth.lunar.client.bridge.impl.type.keyboard;

import com.moonsworth.lunar.bridge.lunar.input.KeyType;
import com.moonsworth.lunar.bridge.lunar.input.KeyboardBridge;
import org.lwjgl.input.Keyboard;
import org.lwjgl.input.Mouse;

public class KeyboardImplementation implements KeyboardBridge {
    public boolean lIlIlIlIlIIlIIlIIllIIIIIl(KeyType var1) {
        if (var1 == KeyType.KEY_NONE) {
            return false;
        } else {
            int var2 = llIlllIIIllllIIlllIllIIIl(var1);
            return var2 < 0 ? Mouse.isButtonDown(var2 + 100) : Keyboard.isKeyDown(llIlllIIIllllIIlllIllIIIl(var1));
        }
    }

    public String IlllIIIIIIlllIlIIlllIlIIl(KeyType var1) {
        return Keyboard.getKeyName(llIlllIIIllllIIlllIllIIIl(var1));
    }

    public boolean lIlIlIlIlIIlIIlIIllIIIIIl() {
        return Keyboard.areRepeatEventsEnabled();
    }

    public void lIlIlIlIlIIlIIlIIllIIIIIl(boolean var1) {
        Keyboard.enableRepeatEvents(var1);
    }

    public int lIllIlIIIlIIIIIIIlllIlIll(KeyType var1) {
        return llIlllIIIllllIIlllIllIIIl(var1);
    }

    public static int llIlllIIIllllIIlllIllIIIl(KeyType var0) {
        switch (var0) {
        case KEY_LWINDOWS:
        case KEY_LCOMMAND:
            return 219;
        case KEY_RWINDOWS:
        case KEY_RCOMMAND:
            return 220;
        case KEY_NONE:
            return 0;
        case KEY_0:
            return 11;
        case KEY_1:
            return 2;
        case KEY_2:
            return 3;
        case KEY_3:
            return 4;
        case KEY_4:
            return 5;
        case KEY_5:
            return 6;
        case KEY_6:
            return 7;
        case KEY_7:
            return 8;
        case KEY_8:
            return 9;
        case KEY_9:
            return 10;
        case KEY_A:
            return 30;
        case KEY_B:
            return 48;
        case KEY_C:
            return 46;
        case KEY_D:
            return 32;
        case KEY_E:
            return 18;
        case KEY_F:
            return 33;
        case KEY_G:
            return 34;
        case KEY_H:
            return 35;
        case KEY_I:
            return 23;
        case KEY_J:
            return 36;
        case KEY_K:
            return 37;
        case KEY_L:
            return 38;
        case KEY_M:
            return 50;
        case KEY_N:
            return 49;
        case KEY_O:
            return 24;
        case KEY_P:
            return 25;
        case KEY_Q:
            return 16;
        case KEY_R:
            return 19;
        case KEY_S:
            return 31;
        case KEY_T:
            return 20;
        case KEY_U:
            return 22;
        case KEY_V:
            return 47;
        case KEY_W:
            return 17;
        case KEY_X:
            return 45;
        case KEY_Y:
            return 21;
        case KEY_Z:
            return 44;
        case KEY_FUNCTION:
            return 196;
        case KEY_RMENU:
            return 184;
        case KEY_LMENU:
            return 56;
        case KEY_LCONTROL:
            return 29;
        case KEY_RSHIFT:
            return 54;
        case KEY_LSHIFT:
            return 42;
        case KEY_RETURN:
            return 28;
        case KEY_ESCAPE:
            return 1;
        case KEY_TAB:
            return 15;
        case KEY_UP:
            return 200;
        case KEY_BACK:
            return 14;
        case KEY_LEFT:
            return 203;
        case KEY_RIGHT:
            return 205;
        case KEY_PGUP:
            return 201;
        case KEY_PGDOWN:
            return 209;
        case KEY_PG:
            return 221;
        case KEY_PRINTSC:
            return 183;
        case KEY_HOME:
            return 199;
        case KEY_END:
            return 207;
        case KEY_DELETE:
            return 211;
        case KEY_DOWN:
            return 208;
        case KEY_F1:
            return 59;
        case KEY_F2:
            return 60;
        case KEY_F3:
            return 61;
        case KEY_F4:
            return 62;
        case KEY_F5:
            return 63;
        case KEY_F6:
            return 64;
        case KEY_F7:
            return 65;
        case KEY_F8:
            return 66;
        case KEY_F9:
            return 67;
        case KEY_F10:
            return 68;
        case KEY_F11:
            return 87;
        case KEY_F12:
            return 88;
        case KEY_SPACE:
            return 57;
        case KEY_GRAVE:
            return 41;
        case KEY_MINUS:
            return 12;
        case KEY_EQUALS:
            return 13;
        case KEY_LBRACKET:
            return 26;
        case KEY_RBRACKET:
            return 27;
        case KEY_SEMICOLON:
            return 39;
        case KEY_APOSTROPHE:
            return 40;
        case KEY_BACKSLASH:
            return 43;
        case KEY_COMMA:
            return 51;
        case KEY_PERIOD:
            return 52;
        case KEY_SLASH:
            return 53;
        case KEY_MULTIPLY:
            return 55;
        case KEY_CAPITAL:
            return 58;
        case KEY_NUMLOCK:
            return 69;
        case KEY_SCROLL:
            return 70;
        case KEY_NUMPAD7:
            return 71;
        case KEY_NUMPAD8:
            return 72;
        case KEY_NUMPAD9:
            return 73;
        case KEY_SUBTRACT:
            return 74;
        case KEY_NUMPAD4:
            return 75;
        case KEY_NUMPAD5:
            return 76;
        case KEY_NUMPAD6:
            return 77;
        case KEY_ADD:
            return 78;
        case KEY_NUMPAD1:
            return 79;
        case KEY_NUMPAD2:
            return 80;
        case KEY_NUMPAD3:
            return 81;
        case KEY_NUMPAD0:
            return 82;
        case KEY_DECIMAL:
            return 83;
        case KEY_F13:
            return 100;
        case KEY_F14:
            return 101;
        case KEY_F15:
            return 102;
        case KEY_F16:
            return 103;
        case KEY_F17:
            return 104;
        case KEY_F18:
            return 105;
        case KEY_F19:
            return 113;
        case KEY_CLEAR:
            return 218;
        case KEY_NUMPADEQUALS:
            return 141;
        case KEY_NUMPADENTER:
            return 156;
        case KEY_DIVIDE:
            return 181;
        case KEY_PAUSE:
            return 197;
        case KEY_INSERT:
            return 210;
        case KEY_RCONTROL:
            return 157;
        case KEY_MOUSE1:
            return -100;
        case KEY_MOUSE2:
            return -99;
        case KEY_MOUSE3:
            return -98;
        case KEY_MOUSE4:
            return -97;
        case KEY_MOUSE5:
            return -96;
        default:
            System.err.println("Can't translate key " + var0.name());
            return 0;
        }
    }

    public static KeyType lIlIlIlIlIIlIIlIIllIIIIIl(int var0) {
        switch (var0) {
        case -100:
            return KeyType.KEY_MOUSE1;
        case -99:
            return KeyType.KEY_MOUSE2;
        case -98:
            return KeyType.KEY_MOUSE3;
        case -97:
            return KeyType.KEY_MOUSE4;
        case -96:
            return KeyType.KEY_MOUSE5;
        case -95:
        case -94:
        case -93:
        case -92:
        case -91:
        case -90:
        case -89:
        case -88:
        case -87:
        case -86:
        case -85:
        case -84:
        case -83:
        case -82:
        case -81:
        case -80:
        case -79:
        case -78:
        case -77:
        case -76:
        case -75:
        case -74:
        case -73:
        case -72:
        case -71:
        case -70:
        case -69:
        case -68:
        case -67:
        case -66:
        case -65:
        case -64:
        case -63:
        case -62:
        case -61:
        case -60:
        case -59:
        case -58:
        case -57:
        case -56:
        case -55:
        case -54:
        case -53:
        case -52:
        case -51:
        case -50:
        case -49:
        case -48:
        case -47:
        case -46:
        case -45:
        case -44:
        case -43:
        case -42:
        case -41:
        case -40:
        case -39:
        case -38:
        case -37:
        case -36:
        case -35:
        case -34:
        case -33:
        case -32:
        case -31:
        case -30:
        case -29:
        case -28:
        case -27:
        case -26:
        case -25:
        case -24:
        case -23:
        case -22:
        case -21:
        case -20:
        case -19:
        case -18:
        case -17:
        case -16:
        case -15:
        case -14:
        case -13:
        case -12:
        case -11:
        case -10:
        case -9:
        case -8:
        case -7:
        case -6:
        case -5:
        case -4:
        case -3:
        case -2:
        case -1:
        case 84:
        case 85:
        case 86:
        case 89:
        case 90:
        case 91:
        case 92:
        case 93:
        case 94:
        case 95:
        case 96:
        case 97:
        case 98:
        case 99:
        case 106:
        case 107:
        case 108:
        case 109:
        case 110:
        case 111:
        case 112:
        case 114:
        case 115:
        case 116:
        case 117:
        case 118:
        case 119:
        case 120:
        case 121:
        case 122:
        case 123:
        case 124:
        case 125:
        case 126:
        case 127:
        case 128:
        case 129:
        case 130:
        case 131:
        case 132:
        case 133:
        case 134:
        case 135:
        case 136:
        case 137:
        case 138:
        case 139:
        case 140:
        case 142:
        case 143:
        case 144:
        case 145:
        case 146:
        case 147:
        case 148:
        case 149:
        case 150:
        case 151:
        case 152:
        case 153:
        case 154:
        case 155:
        case 158:
        case 159:
        case 160:
        case 161:
        case 162:
        case 163:
        case 164:
        case 165:
        case 166:
        case 167:
        case 168:
        case 169:
        case 170:
        case 171:
        case 172:
        case 173:
        case 174:
        case 175:
        case 176:
        case 177:
        case 178:
        case 179:
        case 180:
        case 182:
        case 185:
        case 186:
        case 187:
        case 188:
        case 189:
        case 190:
        case 191:
        case 192:
        case 193:
        case 194:
        case 195:
        case 198:
        case 202:
        case 204:
        case 206:
        case 212:
        case 213:
        case 214:
        case 215:
        case 216:
        case 217:
        default:
            System.err.println("Can't translate key " + var0);
            return KeyType.KEY_NONE;
        case 0:
            return KeyType.KEY_NONE;
        case 1:
            return KeyType.KEY_ESCAPE;
        case 2:
            return KeyType.KEY_1;
        case 3:
            return KeyType.KEY_2;
        case 4:
            return KeyType.KEY_3;
        case 5:
            return KeyType.KEY_4;
        case 6:
            return KeyType.KEY_5;
        case 7:
            return KeyType.KEY_6;
        case 8:
            return KeyType.KEY_7;
        case 9:
            return KeyType.KEY_8;
        case 10:
            return KeyType.KEY_9;
        case 11:
            return KeyType.KEY_0;
        case 12:
            return KeyType.KEY_MINUS;
        case 13:
            return KeyType.KEY_EQUALS;
        case 14:
            return KeyType.KEY_BACK;
        case 15:
            return KeyType.KEY_TAB;
        case 16:
            return KeyType.KEY_Q;
        case 17:
            return KeyType.KEY_W;
        case 18:
            return KeyType.KEY_E;
        case 19:
            return KeyType.KEY_R;
        case 20:
            return KeyType.KEY_T;
        case 21:
            return KeyType.KEY_Y;
        case 22:
            return KeyType.KEY_U;
        case 23:
            return KeyType.KEY_I;
        case 24:
            return KeyType.KEY_O;
        case 25:
            return KeyType.KEY_P;
        case 26:
            return KeyType.KEY_LBRACKET;
        case 27:
            return KeyType.KEY_RBRACKET;
        case 28:
            return KeyType.KEY_RETURN;
        case 29:
            return KeyType.KEY_LCONTROL;
        case 30:
            return KeyType.KEY_A;
        case 31:
            return KeyType.KEY_S;
        case 32:
            return KeyType.KEY_D;
        case 33:
            return KeyType.KEY_F;
        case 34:
            return KeyType.KEY_G;
        case 35:
            return KeyType.KEY_H;
        case 36:
            return KeyType.KEY_J;
        case 37:
            return KeyType.KEY_K;
        case 38:
            return KeyType.KEY_L;
        case 39:
            return KeyType.KEY_SEMICOLON;
        case 40:
            return KeyType.KEY_APOSTROPHE;
        case 41:
            return KeyType.KEY_GRAVE;
        case 42:
            return KeyType.KEY_LSHIFT;
        case 43:
            return KeyType.KEY_BACKSLASH;
        case 44:
            return KeyType.KEY_Z;
        case 45:
            return KeyType.KEY_X;
        case 46:
            return KeyType.KEY_C;
        case 47:
            return KeyType.KEY_V;
        case 48:
            return KeyType.KEY_B;
        case 49:
            return KeyType.KEY_N;
        case 50:
            return KeyType.KEY_M;
        case 51:
            return KeyType.KEY_COMMA;
        case 52:
            return KeyType.KEY_PERIOD;
        case 53:
            return KeyType.KEY_SLASH;
        case 54:
            return KeyType.KEY_RSHIFT;
        case 55:
            return KeyType.KEY_MULTIPLY;
        case 56:
            return KeyType.KEY_LMENU;
        case 57:
            return KeyType.KEY_SPACE;
        case 58:
            return KeyType.KEY_CAPITAL;
        case 59:
            return KeyType.KEY_F1;
        case 60:
            return KeyType.KEY_F2;
        case 61:
            return KeyType.KEY_F3;
        case 62:
            return KeyType.KEY_F4;
        case 63:
            return KeyType.KEY_F5;
        case 64:
            return KeyType.KEY_F6;
        case 65:
            return KeyType.KEY_F7;
        case 66:
            return KeyType.KEY_F8;
        case 67:
            return KeyType.KEY_F9;
        case 68:
            return KeyType.KEY_F10;
        case 69:
            return KeyType.KEY_NUMLOCK;
        case 70:
            return KeyType.KEY_SCROLL;
        case 71:
            return KeyType.KEY_NUMPAD7;
        case 72:
            return KeyType.KEY_NUMPAD8;
        case 73:
            return KeyType.KEY_NUMPAD9;
        case 74:
            return KeyType.KEY_SUBTRACT;
        case 75:
            return KeyType.KEY_NUMPAD4;
        case 76:
            return KeyType.KEY_NUMPAD5;
        case 77:
            return KeyType.KEY_NUMPAD6;
        case 78:
            return KeyType.KEY_ADD;
        case 79:
            return KeyType.KEY_NUMPAD1;
        case 80:
            return KeyType.KEY_NUMPAD2;
        case 81:
            return KeyType.KEY_NUMPAD3;
        case 82:
            return KeyType.KEY_NUMPAD0;
        case 83:
            return KeyType.KEY_DECIMAL;
        case 87:
            return KeyType.KEY_F11;
        case 88:
            return KeyType.KEY_F12;
        case 100:
            return KeyType.KEY_F13;
        case 101:
            return KeyType.KEY_F14;
        case 102:
            return KeyType.KEY_F15;
        case 103:
            return KeyType.KEY_F16;
        case 104:
            return KeyType.KEY_F17;
        case 105:
            return KeyType.KEY_F18;
        case 113:
            return KeyType.KEY_F19;
        case 141:
            return KeyType.KEY_NUMPADEQUALS;
        case 156:
            return KeyType.KEY_NUMPADENTER;
        case 157:
            return KeyType.KEY_RCONTROL;
        case 181:
            return KeyType.KEY_DIVIDE;
        case 183:
            return KeyType.KEY_PRINTSC;
        case 184:
            return KeyType.KEY_RMENU;
        case 196:
            return KeyType.KEY_FUNCTION;
        case 197:
            return KeyType.KEY_PAUSE;
        case 199:
            return KeyType.KEY_HOME;
        case 200:
            return KeyType.KEY_UP;
        case 201:
            return KeyType.KEY_PGUP;
        case 203:
            return KeyType.KEY_LEFT;
        case 205:
            return KeyType.KEY_RIGHT;
        case 207:
            return KeyType.KEY_END;
        case 208:
            return KeyType.KEY_DOWN;
        case 209:
            return KeyType.KEY_PGDOWN;
        case 210:
            return KeyType.KEY_INSERT;
        case 211:
            return KeyType.KEY_DELETE;
        case 218:
            return KeyType.KEY_CLEAR;
        case 219:
            if (System.getProperty("os.name").toLowerCase().contains("mac")) {
                return KeyType.KEY_LCOMMAND;
            }

            return KeyType.KEY_LWINDOWS;
        case 220:
            if (System.getProperty("os.name").toLowerCase().contains("mac")) {
                return KeyType.KEY_RCOMMAND;
            }

            return KeyType.KEY_RWINDOWS;
        case 221:
            return KeyType.KEY_PG;
        }
    }
}